name: Run Django Tests
on: [push, pull_request]
jobs:
  Set-up-Django-Project:
    runs-on : ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version:
        - "3.12"

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '2'

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version}}

    - uses: browser-actions/setup-firefox@latest
    - run: firefox --version

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Migrations
      run: |
        python manage.py migrate

    - name: Run Django Tests
      run: |
        pytest --cov

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
